CREATE DATABASE IF NOT EXISTS sweetfish DEFAULT CHARACTER SET utf8;
SET NAMES 'utf8';
USE sweetfish;

CREATE TABLE TOKEN(
  id INT NOT NULL AUTO_INCREMENT COMMENT '唯一id',
  token VARCHAR(128) NOT NULL COMMENT 'token',
  username VARCHAR(128) NOT NULL COMMENT 'token对应的username',
  expire_time DATETIME NOT NULL COMMENT 'token过期时间',
  PRIMARY KEY (id),
  KEY (token)
) ENGINE = INNODB;

-- 基于用户名密码的用户信息，兼容openid
CREATE TABLE USER_AUTH_INFO (
    id INT NOT NULL AUTO_INCREMENT COMMENT 'id',
    username VARCHAR(128) NOT NULL COMMENT '用户名',
    password VARCHAR(1024) NOT NULL COMMENT '密码',
    PRIMARY KEY (id),
    UNIQUE KEY(username)
) ENGINE = INNODB;

CREATE TABLE USER_PROJECT (
  id INT NOT NULL AUTO_INCREMENT COMMENT 'id',
  username VARCHAR(128) NOT NULL COMMENT '用户名',
  projectId INT NOT NULL COMMENT '项目ID',
  PRIMARY KEY(id),
  UNIQUE KEY(username, projectId)
) ENGINE = INNODB;

CREATE TABLE PROJECT (
  id INT NOT NULL AUTO_INCREMENT COMMENT 'id',
  fullName VARCHAR(128) NOT NULL COMMENT 'GitHub项目全称',
  status VARCHAR(64) NOT NULL COMMENT '状态',
  sourceCodeIp VARCHAR(16) NOT NULL COMMENT '源码所在主机',
  config VARCHAR(4096) NOT NULL COMMENT '项目配置',
  PRIMARY KEY(id)
) ENGINE = INNODB;